### ISSUE TITLE
RDKit / OBChem read JSON?

### ISSUE THREAD

**Issue by swamidass** [mcs07/CommonChem#2]
Great project. I wanted to know if RDKit supports reading JSON format.

Also, different question, what process you have for proposing enhancements.

**Comment by greglandrum** [comment]
The RDKit supports a JSON format which is derived from CommonChem:
```
In [3]: from rdkit.Chem import rdMolInterchange

In [4]: m = Chem.MolFromSmiles("Oc1ccccc1")
jso
In [5]: json = rdMolInterchange.MolToJSON(m)

In [6]: nm = rdMolInterchange.JSONToMols(json)[0]

In [7]: Chem.MolToSmiles(nm)
Out[7]: 'Oc1ccccc1'

In [8]: print(json)
{"commonchem":{"version":10},"defaults":{"atom":{"z":6,"impHs":0,"chg":0,"nRad":0,"isotope":0,"stereo":"unspecified"},"bond":{"bo":1,"stereo":"unspecified"}},"molecules":[{"atoms":[{"z":8,"impHs":1},{},{"impHs":1},{"impHs":1},{"impHs":1},{"impHs":1},{"impHs":1}],"bonds":[{"atoms":[0,1]},{"bo":2,"atoms":[1,2]},{"atoms":[2,3]},{"bo":2,"atoms":[3,4]},{"atoms":[4,5]},{"bo":2,"atoms":[5,6]},{"atoms":[6,1]}],"extensions":[{"name":"rdkitRepresentation","formatVersion":2,"toolkitVersion":"2022.03.5","aromaticAtoms":[1,2,3,4,5,6],"aromaticBonds":[1,2,3,4,5,6],"cipRanks":[4,3,2,1,0,1,2],"atomRings":[[1,6,5,4,3,2]]}]}]}
```
This doesn't support 100% of the RDKit's features, but it's a great interchange format for "normal" molecules (i.e. things without query features).

If you have suggestions for extensions to commonchem itself you could make them here; if there's something missing in the RDKit's JSON format, then I'd suggest opening an issue in the RDKit issue tracker
